connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris-proxy:8282/api/catalog
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwb2xhcmlzIiwic3ViIjoicm9vdCIsImlhdCI6MTc3NjczMzY2MiwiZXhwIjoxNzc2NzM3MjYyLCJqdGkiOiI3OTA1YWRmNS1kNDI1LTQ3MTctOTgyOS1kODcwOTYyNGJhMGYiLCJhY3RpdmUiOnRydWUsImNsaWVudF9pZCI6IjhhMWU3N2U5MDg3NmU4NDkiLCJwcmluY2lwYWxJZCI6MSwic2NvcGUiOiJQUklOQ0lQQUxfUk9MRTpBTEwifQ.RAcmy5mnXT_-je7tIGhV3hBjiTBTlzvTgSVll6DVz1f1CRW8g2zgTSLR4ddiZo_lhqfTvEpLFfDC1kMRi9PoFthjJkt8H6kRVUPT3Il9r65eZtflfdRfNXgkkfn6oMP9VmkYKp3Fp0EF4BVy99G744-fc0H083cYKC6S6h-bd4RyMpP1mLN82AJ08EuhE5B2eT3zqSTBnfTF7cNUZYO0-WkI-a-uhCpPqdam9R3Zrluj4Dzbx70D0qg_rVoQ83B3vZfq-axg06EoqOaGZ8R1nJHllUe00wO47cH0gE68WT51tuL5BoAG9omkRo5WDf42CtFoEfpNWqkpI0IZwIOZlw
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=admin
hive.s3.aws-secret-key=password
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
hive.s3.region=us-east-1
